apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: hunt-backend
  namespace: pod-hunt
  labels:
    app: hunt-backend
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: registry.fedoraproject.org/f29/golang
    name: "golang1.11"
    referencePolicy:
      type: Local
  - from:
      kind: DockerImage
      name: centos:7
    name: "centos7"
    referencePolicy:
      type: Source
