apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: hunt-ui
  namespace: pod-hunt
  labels:
    app: hunt-ui
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: registry.access.redhat.com/ubi8/nodejs-10
    name: nodejs10
    referencePolicy:
      type: Local
  - from:
      kind: DockerImage
      name: registry.access.redhat.com/rhel8/nginx-114
    generation: 1
    importPolicy: {}
    name: nginx1.14
    referencePolicy:
      type: Local
