apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    component: backend
  name: hunt-backend-src
  namespace: pod-hunt
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: hunt-backend:src
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/vrutkovs/k8s-podhunt
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: hunt-backend:golang1.11
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
